name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ["7.3", "7.4"]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: json, zip
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: "Test: PHPUnit unit-test"
        run: vendor/bin/phpunit --testsuite unit-test --coverage-clover=coverage.xml

      - name: "Test: PHPUnit serializer-test"
        run: vendor/bin/phpunit --testsuite serializer-test

      - name: "Test: Coverage Check"
        run: vendor/bin/coverage-check coverage.xml 100

      - name: "Test: PHP Codesniffer"
        run: vendor/bin/phpcs -np --colors

      - name: "Test: PHPStan"
        run: vendor/bin/phpstan analyse --no-interaction
