name: CI
on:
  - push
  - pull_request
jobs:

  coding-guidelines:
    name: Coding Guidelines
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: json, zip
          tools: cs2pr
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Update dependencies
        run: composer update --no-progress --no-interaction --prefer-dist --optimize-autoloader
      - name: Run phpcs
        run: vendor/bin/phpcs -q --report=checkstyle | cs2pr

  type-checker:
    name: Type Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: json, zip
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Update dependencies
        run: composer update --no-progress --no-interaction --prefer-dist --optimize-autoloader
      - name: Run phpstan
        run: vendor/bin/phpstan analyse --no-interaction

  tests:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-latest
        php-versions:
          - 7.3
          - 7.4
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: json, zip
          coverage: xdebug
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Update dependencies
        run: composer update --no-progress --no-interaction --prefer-dist --optimize-autoloader
      - name: Run phpunit --testsuite unit-test
        run: vendor/bin/phpunit --testsuite unit-test --coverage-clover=coverage.xml
      - name: Run phpunit --testsuite serializer-test
        run: vendor/bin/phpunit --testsuite serializer-test
